version: "3.8"

services:
  app:
    image: cornellappdev/hustle-dev:${IMAGE_TAG}
    env_file: .env
    volumes:
      - ./service-account-key.json:/service-account-key.json
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager